spring:
  main:
    banner-mode: off

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

app:
  server:
    url: ${app.server.url}

springdoc:
  webjars:
    prefix:
  swagger-ui:
    path: "/"
    disable-swagger-default-url: true
    url: /v3/api-docs.yaml
